### ISSUE TITLE
where can I find the "scannetv2-labels.combined.tsv"?

### ISSUE THREAD

**Issue by Liusifei** [angeladai/3DMV#2]

**Comment by Liusifei** [comment]
Incorrectly used a modified version, which does not fit to this project. Solved.

**Comment by Shubodh** [comment]
Hi, @Liusifei I am facing the same issue. What do you mean "used a modified version"?

After downloading ScanNet data, using the "prepare_2D_data.py" script I was able to extract RGB, D and pose but not segmentation labels (which asks for the above file when using the flag --export_label_images"). How could you proceed?

**Comment by yakaib** [comment]
I meeted the same problem，how can i solved it？

**Comment by fsted** [comment]
I meet the same problem,how to solve it?
